services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: atelier-sequelize-test
    ports:
      - 3306:3306
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
